name: eventos_app
description: EVENTOS - Event Planning and Booking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10  # or latest
  http: ^1.2.0
  shared_preferences: ^2.2.3
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:

  
    - assets/svg/eventos_logo.svg
